POST http://localhost:8080/login
Content-Type: application/json

{
    "username":"Elsokkary101",
    "password":"1234"
}
###

GET http://localhost:8080/Course/635937cd9356af97449214a4

###

GET http://localhost:3000/login